# Generated by Django 3.2.9 on 2023-07-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ellipse',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Компаний'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='countries',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Стран'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='exhibitors',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Экспонентов'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='meetings',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='B2B встречи'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок форма'),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=300, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pageone',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок Экспо'),
        ),
        migrations.AlterField(
            model_name='pageone',
            name='year',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название партнёра'),
        ),
        migrations.AlterField(
            model_name='placeoffice',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название спонсара'),
        ),
        migrations.AlterField(
            model_name='target',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок цели'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='number',
            field=models.CharField(max_length=300, verbose_name='Номер задач'),
        ),
    ]
