# Generated by Django 3.2.9 on 2023-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_app_en', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationen',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка для локации'),
        ),
    ]
