# Generated by Django 3.2.9 on 2023-07-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='apps/news/images', verbose_name='Фотография')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('urls', models.URLField(blank=True, null=True, verbose_name='Укажите urel ссылку')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Укажите дату')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
    ]
