# Generated by Django 3.2.9 on 2023-07-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address_en',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_ru',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mail',
            field=models.EmailField(max_length=300, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(max_length=300, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='price',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='stand',
            name='square',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='status',
            field=models.CharField(choices=[['GENERAL', 'GENERAL'], ['PLATINUM+', 'PLATINUM+'], ['PLATINUM', 'PLATINUM'], ['Gold+', 'Gold+'], ['Gold', 'Gold'], ['SILVER+', 'SILVER+'], ['SILVER', 'SILVER'], ['STANDARD+', 'STANDARD+'], ['STANDARD', 'STANDARD']], default=None, max_length=300, verbose_name='Тип стендов'),
        ),
    ]
