# Generated by Django 3.2.9 on 2023-07-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_app', '0002_auto_20230717_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='price',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Цена'),
        ),
    ]
