# Generated by Django 3.2.9 on 2023-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.BooleanField(default=False, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='news_portals',
            field=models.BooleanField(default=False, verbose_name='Новостные порталы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='other_one',
            field=models.BooleanField(default=False, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='user',
            name='other_two',
            field=models.BooleanField(default=False, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='user',
            name='participation',
            field=models.BooleanField(default=False, verbose_name='Участие на HIT EXPO'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$UksGNFXfnUTmuks4wlm3Ga$dU3ZAXOApjbVrji2+sTv4Af4sHXP02uqD+jDVAo8WJg=', max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.BooleanField(default=False, verbose_name='Поиске проектов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_radio',
            field=models.BooleanField(default=False, verbose_name='ТВ, Радио'),
        ),
        migrations.AlterField(
            model_name='user',
            name='visit',
            field=models.BooleanField(default=False, verbose_name='Посещение на HIT EXPO'),
        ),
    ]
