# Generated by Django 3.2.9 on 2023-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_participant',
            field=models.EmailField(blank=True, default=None, max_length=300, null=True, unique=True, verbose_name='Email Participant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_smi',
            field=models.EmailField(blank=True, default=None, max_length=300, null=True, unique=True, verbose_name='Email SMI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workEmail',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Work Email'),
        ),
    ]
