# Generated by Django 3.2.9 on 2023-06-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_id_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/passport_one', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_id_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/passport_three', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_id_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/passport_two', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='news_portals',
            field=models.BooleanField(default=1, verbose_name='Новостные порталы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='other_one',
            field=models.BooleanField(default=1, verbose_name='Другое'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='other_two',
            field=models.BooleanField(default=1, verbose_name='Другое'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='participation',
            field=models.BooleanField(default=1, verbose_name='Участие на HIT EXPO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.BooleanField(default=1, verbose_name='Поиске проектов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tv_radio',
            field=models.BooleanField(default=1, verbose_name='ТВ, Радио'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='visit',
            field=models.BooleanField(default=1, verbose_name='Посещение на HIT EXPO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$CE0tr4HuDM1Q22hvAOFkNf$n3NyUQe4uA1lyIOnwViNIql8T3wzJjyXtbhGhOi+i1g=', max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personalPhone',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workPhone',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Телефон'),
        ),
    ]
