# Generated by Django 3.2.9 on 2023-06-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230614_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='dop_participant',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participation_sector',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mass_media',
        ),
        migrations.RemoveField(
            model_name='user',
            name='participant',
        ),
        migrations.AddField(
            model_name='user',
            name='address_participant',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_smi',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='agricultural_production',
            field=models.BooleanField(default=False, verbose_name='Производство + сельхоз'),
        ),
        migrations.AddField(
            model_name='user',
            name='banks',
            field=models.BooleanField(default=False, verbose_name='Банки'),
        ),
        migrations.AddField(
            model_name='user',
            name='bik',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='user',
            name='brand',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование бренда'),
        ),
        migrations.AddField(
            model_name='user',
            name='choose_direction_expert',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='user',
            name='choose_direction_fashion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Выберите направление (Fashion)'),
        ),
        migrations.AddField(
            model_name='user',
            name='choose_direction_food',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Выберите направление (Food)'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Деятельность компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='construction',
            field=models.BooleanField(default=False, verbose_name='Строительство'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='user',
            name='echo',
            field=models.BooleanField(default=False, verbose_name='Эко'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.BooleanField(default=False, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_participant',
            field=models.EmailField(blank=True, default=None, max_length=300, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_smi',
            field=models.EmailField(blank=True, default=None, max_length=300, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_certificate_smi',
            field=models.ImageField(blank=True, null=True, upload_to='images/certificate-smi', verbose_name='Загрузите вашего журналистского удостоверения в  png или jpg'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo-smi', verbose_name='Загрузите логотип компании в png или jpg'),
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.BooleanField(default=False, verbose_name='Текстильное промышленность'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='it',
            field=models.BooleanField(default=False, verbose_name='IT'),
        ),
        migrations.AddField(
            model_name='user',
            name='kfx',
            field=models.BooleanField(default=False, verbose_name='КФХ'),
        ),
        migrations.AddField(
            model_name='user',
            name='krc',
            field=models.BooleanField(default=False, verbose_name='КРС'),
        ),
        migrations.AddField(
            model_name='user',
            name='machinery',
            field=models.BooleanField(default=False, verbose_name='Машиностроение'),
        ),
        migrations.AddField(
            model_name='user',
            name='medicine',
            field=models.BooleanField(default=False, verbose_name='Медицина'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_contact_person',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_manager',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ф.И.О руководителя'),
        ),
        migrations.AddField(
            model_name='user',
            name='okpo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_participant',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное юридическое наименование организации'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_smi',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное юридическое наименование организации'),
        ),
        migrations.AddField(
            model_name='user',
            name='p_c',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Р/С'),
        ),
        migrations.AddField(
            model_name='user',
            name='participant_sector',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='В качестве кого вы хотите посетить HIT EXPO ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='participation_sector',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Выберите сектор участия (с условиями участия каждого сектора можно ознакомится)'),
        ),
        migrations.AddField(
            model_name='user',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='file/register', verbose_name='Загрузите свидетельство регистрации в pdf'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_contact_person',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='position_contact_person',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='position_main',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='smi_team',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сколько у вас человек в команде?'),
        ),
        migrations.AddField(
            model_name='user',
            name='technique',
            field=models.BooleanField(default=False, verbose_name='Строительство + техника'),
        ),
        migrations.AddField(
            model_name='user',
            name='textiles',
            field=models.BooleanField(default=False, verbose_name='Текстиль, обувь и аксессуары'),
        ),
        migrations.AddField(
            model_name='user',
            name='tourism',
            field=models.BooleanField(default=False, verbose_name='Туризм'),
        ),
        migrations.AddField(
            model_name='user',
            name='trade',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Выберите отрасль'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='user',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_contact_person',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_phone',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$xBLEIYnMlYFAiUfhO9TjJA$9wONPa4E6xknQaAQE0uEAYH/zNetmMAOwBu7O8iQzeI=', max_length=128, verbose_name='Пароль'),
        ),
        migrations.DeleteModel(
            name='DopParticipant',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='MassMedia',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='ParticipationSector',
        ),
    ]
