# Generated by Django 3.2.9 on 2023-07-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230715_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_id_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_id_three',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_id_two',
        ),
    ]
