# Generated by Django 3.2.9 on 2023-06-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230615_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='workEmail',
            new_name='workemail',
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_bool',
            field=models.BooleanField(default=False, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$OBPof2RoTdUacF9hXnU4Vv$y7KAv8ZI89aQFsJVmmLHrfzXxyFPNWnQHGsGwXGvKN8=', max_length=128, verbose_name='Пароль'),
        ),
    ]
