# Generated by Django 3.2.9 on 2023-06-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230615_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='workemail',
            new_name='workEmail',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$iFfZZn4RvqWqZ9vuA2ISZx$PM7B55zUi65JZcAhSalo4VshCCW+kjjEsz2y/3UUQX8=', max_length=128, verbose_name='Пароль'),
        ),
    ]
