# Generated by Django 3.2.9 on 2023-07-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230619_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_user',
            field=models.CharField(default=1, max_length=128, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$E4mOTUw2YQOKo7FfuMDmtj$Jh2uDqg1Xsp3wCBelj4udRG+V9xwusadY0qcwGlJH2w=', max_length=128, verbose_name='Пароль'),
        ),
    ]
