# Generated by Django 3.2.9 on 2023-07-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230704_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatarHidden',
        ),
        migrations.RemoveField(
            model_name='user',
            name='news_portals',
        ),
        migrations.AddField(
            model_name='user',
            name='ad_city',
            field=models.BooleanField(default=False, verbose_name='Наружная реклама в городе'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_eight',
            field=models.BooleanField(default=False, verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_five',
            field=models.BooleanField(default=False, verbose_name='Возможность получения инвестиции'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_for',
            field=models.BooleanField(default=False, verbose_name='Реализация продукции'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_nine',
            field=models.BooleanField(default=False, verbose_name='Место и формат проведения'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_one',
            field=models.BooleanField(default=False, verbose_name='Присутствие инвесторов'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_seven',
            field=models.BooleanField(default=False, verbose_name='Коммуникация с другми участниками'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_six',
            field=models.BooleanField(default=False, verbose_name='Расширение бизнеса'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_ten',
            field=models.BooleanField(default=False, verbose_name='Возможность получения номинации'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_three',
            field=models.BooleanField(default=False, verbose_name='Выход на мировой рынок'),
        ),
        migrations.AddField(
            model_name='user',
            name='benefits_two',
            field=models.BooleanField(default=False, verbose_name='Присутствие государственных органов'),
        ),
        migrations.AddField(
            model_name='user',
            name='gos_organization',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_fair',
            field=models.BooleanField(default=False, verbose_name='Приглашение от экспонента выставки'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_mail',
            field=models.BooleanField(default=False, verbose_name='Приглашение от организаторов по почте'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_minister',
            field=models.BooleanField(default=False, verbose_name='Приглашение от Министерства / ведомства'),
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.BooleanField(default=False, verbose_name='Сообщение по тел/факсу от организаторов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$QdiZNuPSmFMwHV68aJ1Sfr$IYoSrvtBZrGag2VEBRYRtpnSqkfSeuCUUtIq1Pi9SNA=', max_length=128, verbose_name='Пароль'),
        ),
    ]
