# Generated by Django 3.2.9 on 2023-07-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230706_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='address_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='active_manager',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Действующий на основании'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_two',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_manager',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Дата рождения (manager)'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_one',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_two',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Юридическое название компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='describe_company',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Опишите свою деятельность (товар или услугу)'),
        ),
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Направление (Напишите свой вид деятельности “Производство кирпичей”)'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn_manager',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ИНН/ИИН руководителя'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_face',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ф.И.О (Контактное лицо)'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_employees',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Количество сотрудников'),
        ),
        migrations.AddField(
            model_name='user',
            name='orgn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ОГРН(Номер патента)'),
        ),
        migrations.AddField(
            model_name='user',
            name='other_trade',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Другое(Введите свою отрасль если не нашли среди предложенных)'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_face',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Номер телефона: (Контактное лицо)'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_company',
            field=models.ImageField(blank=True, null=True, upload_to='images/company', verbose_name='Загрузите устав компании в  png или jpg'),
        ),
        migrations.AddField(
            model_name='user',
            name='position_manager',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ИНН/ИИН руководителя'),
        ),
        migrations.AddField(
            model_name='user',
            name='selection_face',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Вы являетесь контактным лицом ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='type_register',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='В качестве кого вы хотите посетить HIT EXPO?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ИИН/ИНН(Серия патента компании)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$xrntVxt3h07IW2VrarGuBm$iS/lVgneKwImz3v+mlG4RDP3rqT6j+tvi5Ecv3Z5c04=', max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trade',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Отрасль (Выберите одну из представленных 'Строительство и недвижимость')"),
        ),
    ]
