# Generated by Django 3.2.9 on 2023-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230712_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tv_radio',
        ),
        migrations.AddField(
            model_name='user',
            name='name_bank',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование банка'),
        ),
        migrations.AddField(
            model_name='user',
            name='radio_bool',
            field=models.BooleanField(default=False, verbose_name='Радио'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_bool',
            field=models.BooleanField(default=False, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='tv_bool',
            field=models.BooleanField(default=False, verbose_name='ТВ'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_bool',
            field=models.BooleanField(default=False, verbose_name='Whats App'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$gwIkb9BTQc5QPEsEMLzN0q$ZTF6IhIKQU2azoRyRUwa+AS5vn/oGFmZOZlAOkZ3kvU=', max_length=128, verbose_name='Пароль'),
        ),
    ]
