# Generated by Django 3.2.9 on 2023-07-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user_status',
            field=models.CharField(blank=True, choices=[['Партнер', 'Партнер'], ['Участник', 'Участник'], ['Сми', 'Сми'], ['Спонсор', 'Спонсор']], default=None, max_length=100, null=True, verbose_name='Выберите направление'),
        ),
    ]
