# Generated by Django 3.2.9 on 2023-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='data',
            field=models.BooleanField(default=False, verbose_name='Я согласен на обработку моих персональных данных'),
        ),
    ]
