# Generated by Django 3.2.9 on 2023-06-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_en', '0004_alter_placeofficeen_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('image', models.ImageField(upload_to='apps/main_page/images/', verbose_name='Фотография')),
                ('title_one', models.CharField(blank=True, max_length=64, null=True, verbose_name='Дни')),
                ('title_two', models.CharField(blank=True, max_length=64, null=True, verbose_name='Основа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'zone_en',
            },
        ),
    ]
