# Generated by Django 3.2.9 on 2023-06-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_en', '0005_zoneen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeen',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка для локации'),
        ),
        migrations.AlterField(
            model_name='placeofficeen',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка для локации'),
        ),
    ]
